/*
 * Flashback Export Extras
 * Copyright (C) RethinkQAQ
 *
 * This file is part of Flashback Export Extras.
 *
 * Flashback Export Extras is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * Flashback Export Extras is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Flashback Export Extras. If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: LGPL-3.0-or-later
 */
package com.rethinkqaq.flashbackexportextras;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.rethinkqaq.flashbackexportextras.exporting.CameraPathExporter;
import net.fabricmc.loader.api.FabricLoader;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class FlashbackExportExtrasConfig {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static final Path CONFIG_PATH = FabricLoader.getInstance()
            .getConfigDir().resolve("flashbackexportextras.json");

    public static FlashbackExportExtrasConfig INSTANCE = new FlashbackExportExtrasConfig();

    /** FFmpeg quality preset names offered in the export UI. */
    public static final String[] HDR_QUALITY_PRESETS = {
            "ultrafast", "superfast", "veryfast", "faster", "fast", "medium", "slow", "slower", "veryslow"
    };

    public static final String DEFAULT_QUALITY_PRESET = "medium";

    /** Mutually exclusive export destination selected by the export UI. */
    public ExportMode exportMode = ExportMode.VIDEO;

    /** True = linearize depth from NDC [0,1] to world-space distance. */
    public boolean depthLinearizeWorldSpace = true;

    /** EXR Combined-layer color encoding selected by the user. */
    public ExrColorEncoding exrColorEncoding = ExrColorEncoding.SDR;

    /** Lossless EXR compression preset selected by the user. */
    public ExrCompression exrCompression = ExrCompression.ZIP;

    /** Optional single-level subdirectory name for the EXR sequence. */
    public String exrOutputName = "";

    /** True when exrOutputName was generated by the export window, not typed by the user. */
    public boolean exrOutputNameAutoGenerated = false;

    /** True = export a camera path alongside the selected export. */
    public boolean exportCameraPath = true;

    /** File format used for the optional camera path export. */
    public CameraPathExporter.Format cameraExportFormat = CameraPathExporter.Format.GLB;

    /** True = offset camera path to start at origin. */
    public boolean cameraPathRelativeOrigin = true;

    /** Peak brightness in nits for PQ encoding (default 1000). */
    public int hdrPeakBrightness = 1000;

    /** Paper white brightness in nits (SDR reference level, default 203). Reserved for future use. */
    public int hdrPaperWhiteNits = 203;

    /** FFmpeg quality preset for HDR video export (x264/x265-style names). */
    public String hdrQualityPreset = DEFAULT_QUALITY_PRESET;

    /** Constant-quality (CRF/CQ) value for HDR encoders that support it (lower = better). */
    public int hdrCrf = 18;

    /** True = record export audio in stereo, preserving spatial directionality. */
    public boolean forceStereoAudio = true;

    public enum ExportMode {
        VIDEO,
        EXR,
        HDR10,
        S_LOG3
    }

    /** Color encoding of the EXR Combined layer. */
    public enum ExrColorEncoding {
        /** Standard 8-bit SDR Rec.709/sRGB color. */
        SDR,
        /** Scene-linear Rec.709 HDR color (values above 1.0 preserved). */
        SCENE_LINEAR,
        /** S-Log3 transfer with BT.2020 primaries (matches S-Log3 video export). */
        S_LOG3,
        /** ACEScct log grading encoding with ACES AP1 primaries (AMPAS S-2016-001). */
        ACES_CCT
    }

    public enum ExrCompression {
        ZIP,
        ZIPS,
        NONE
    }

    public ExrCompression getExrCompression() {
        return exrCompression == null ? ExrCompression.ZIP : exrCompression;
    }

    public ExrColorEncoding getExrColorEncoding() {
        return exrColorEncoding == null ? ExrColorEncoding.SDR : exrColorEncoding;
    }

    public CameraPathExporter.Format getCameraExportFormat() {
        return cameraExportFormat == null ? CameraPathExporter.Format.GLB : cameraExportFormat;
    }

    /** Returns a validated HDR quality preset name (see {@link #HDR_QUALITY_PRESETS}). */
    public String getHdrQualityPreset() {
        if (hdrQualityPreset != null) {
            String candidate = hdrQualityPreset.trim().toLowerCase(java.util.Locale.ROOT);
            for (String preset : HDR_QUALITY_PRESETS) {
                if (preset.equals(candidate)) return preset;
            }
        }
        return DEFAULT_QUALITY_PRESET;
    }

    public ExportMode getExportMode() {
        return exportMode == null ? ExportMode.VIDEO : exportMode;
    }

    public void setExportMode(ExportMode mode) {
        exportMode = mode == null ? ExportMode.VIDEO : mode;
    }

    public static void load() {
        if (Files.exists(CONFIG_PATH)) {
            try {
                String json = Files.readString(CONFIG_PATH);
                JsonObject object = JsonParser.parseString(json).getAsJsonObject();
                INSTANCE = GSON.fromJson(object, FlashbackExportExtrasConfig.class);
                if (INSTANCE == null) INSTANCE = new FlashbackExportExtrasConfig();
                // Migrate the two old, independently persisted mode flags.
                // HDR10 keeps precedence to preserve the behaviour of old configs.
                if (!object.has("exportMode")) {
                    if (object.has("hdrExport") && object.get("hdrExport").getAsBoolean()) {
                        INSTANCE.setExportMode(ExportMode.HDR10);
                    } else if (object.has("exportAsExr") && object.get("exportAsExr").getAsBoolean()) {
                        INSTANCE.setExportMode(ExportMode.EXR);
                    }
                }
                // Migrate the temporary boolean used by the first compression
                // option implementation to the new three-level setting.
                if (!object.has("exrCompression") && object.has("exrUncompressed")
                        && object.get("exrUncompressed").getAsBoolean()) {
                    INSTANCE.exrCompression = ExrCompression.NONE;
                }
                // Migrate the old scene-linear checkbox to the new color
                // encoding selector (SDR / scene-linear / S-Log3).
                if (!object.has("exrColorEncoding") && object.has("exrSceneLinearHdr")
                        && object.get("exrSceneLinearHdr").getAsBoolean()) {
                    INSTANCE.exrColorEncoding = ExrColorEncoding.SCENE_LINEAR;
                }
                // Older configs did not distinguish an automatic timestamp
                // from a name entered by the user. Recover the old automatic
                // form once so it can be refreshed on the next window open.
                if (!object.has("exrOutputNameAutoGenerated")) {
                    INSTANCE.exrOutputNameAutoGenerated = isAutoGeneratedExrName(INSTANCE.exrOutputName);
                }
            } catch (IOException | RuntimeException e) {
                Path backup = backupInvalidConfig();
                FlashbackExportExtras.LOGGER.error(
                        "Failed to load config; using defaults. Invalid config backup: {}",
                        backup == null ? "unavailable" : backup, e);
                INSTANCE = new FlashbackExportExtrasConfig();
            }
        }
        save();
    }

    public static boolean isAutoGeneratedExrName(String value) {
        return value != null && value.trim().matches("\\d{4}-\\d{2}-\\d{2}T_\\d{2}_\\d{2}");
    }

    private static Path backupInvalidConfig() {
        if (!Files.exists(CONFIG_PATH)) return null;
        String timestamp = DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss")
                .format(LocalDateTime.now());
        Path backup = CONFIG_PATH.resolveSibling("flashbackexportextras.invalid-" + timestamp + ".json");
        try {
            return Files.copy(CONFIG_PATH, backup, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException backupError) {
            FlashbackExportExtras.LOGGER.error("Failed to back up invalid config", backupError);
            return null;
        }
    }

    public static void save() {
        try {
            Files.createDirectories(CONFIG_PATH.getParent());
            Files.writeString(CONFIG_PATH, GSON.toJson(INSTANCE));
        } catch (IOException e) {
            FlashbackExportExtras.LOGGER.error("Failed to save config", e);
        }
    }
}
